services:
  mongo:
    image: mongo
    ports:
      - "27017:27017" # DEVELOPMENT ONLY
    expose:
      - "27017"
    volumes:
      - mongo-db:/data/db

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" # DEVELOPMENT ONLY
    expose:
      - "9200"
    volumes:
      - es-db:/usr/share/elasticsearch/data

volumes:
  mongo-db:
  es-db:
